baseURL = "https://blog-github.zhangeek.com/"

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "LoveIt"

# 网站标题
title = "我的全新 Hugo 网站"

# 网站语言, 仅在这里 CN 大写 ["en", "zh-CN", "fr", "pl", ...]
languageCode = "zh-CN"
# 语言名称 ["English", "简体中文", "Français", "Polski", ...]
languageName = "简体中文"
# 是否包括中日韩文字
hasCJKLanguage = true

# 作者配置
[author]
email = ""
link = ""
name = "xxxx"

# 菜单配置
[menu]
[[menu.main]]
identifier = "posts"
weight = 1
# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
pre = ""
# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
name = "文章"
post = ""
url = "/posts/"
# 当你将鼠标悬停在此菜单链接上时, 将显示的标题
title = ""
[[menu.main]]
identifier = "tags"
name = "标签"
post = ""
pre = ""
title = ""
url = "/tags/"
weight = 2
[[menu.main]]
identifier = "categories"
name = "分类"
post = ""
pre = ""
title = ""
url = "/categories/"
weight = 3

# Hugo 解析文档的配置
[markup]
# 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
[markup.highlight]
# false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
noClasses = false

# baseURL = "https://blog-github.zhangeek.com/"
# languageCode = "zh-cn"
# title = "Vczyh's Blog"
# theme = "yinyang"
# DefaultContentLanguage = "cn"

# [markup]
#   defaultMarkdownHandler = 'goldmark'
#   [markup.goldmark]
#     [markup.goldmark.extensions]
#       definitionList = true
#       footnote = true
#       linkify = true
#       linkifyProtocol = 'https'
#       strikethrough = true
#       table = true
#       taskList = true
#       typographer = true
#     [markup.goldmark.parser]
#       autoHeadingID = true
#       autoHeadingIDType = 'github'
#       # [markup.goldmark.parser.attribute]
#       #   block = false
#       #   title = true
#     [markup.goldmark.renderer]
#       hardWraps = false
#       unsafe = false
#       xhtml = false
#   [markup.highlight]
#     guessSyntax = true
#     noClasses = true
#     style = "tango"
#     tabWidth = 2

#     # anchorLineNos = false
#     # codeFences = true
#     # guessSyntax = false
#     # hl_Lines = ''
#     # lineAnchors = ''
#     # lineNoStart = 1
#     # lineNos = false
#     # lineNumbersInTable = true
#     # noClasses = true
#     # noHl = false
#     # style = 'github'
#     # tabWidth = 2

# [author]
#   name = "vczyh"
#   homepage = "https://zhangeek.com/"

# [languages]
#   # [languages.en]
#   #   contentDir = "content/en"
#   #   languageName = "English"
#   #   weight = 1
#   [languages.cn]
#     contentDir = "content"
#     languageName = "Chinese"
#     weight = 2

# [params]
# mainSections = ["posts"]
# headTitle = "vczyh"
# disqus = "vczyh" # disqus account name
# extraHead = '<script async src="https://www.googletagmanager.com/gtag/js?id=UA-xxx"></script>'
# [[params.socials]]
# name = "About Me"
# link = "https://github.com/vczyh"
# [[params.socials]]
# name = "Github"
# link = "https://github.com/vczyh"
# postHeaderContent = ""
# postFooterContent = "<br/><br/><p>Subscribe to：<a target='_blank' href='https://mailchi.mp/a1a0d59e7a19/joway'>Joway's Blog</a></p>"
# extraCSSFiles = ["css/foo.css", "css/bar.css"]
# extraCSSFiles = []
