baseURL = "https://blog-github.zhangeek.com/"
languageCode = "zh-cn"
title = "Vczyh's Blog"
theme = "yinyang"
DefaultContentLanguage = "cn"

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      # [markup.goldmark.parser.attribute]
      #   block = false
      #   title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
  [markup.highlight]
    guessSyntax = true
    noClasses = true
    style = "tango"
    tabWidth = 2

    # anchorLineNos = false
    # codeFences = true
    # guessSyntax = false
    # hl_Lines = ''
    # lineAnchors = ''
    # lineNoStart = 1
    # lineNos = false
    # lineNumbersInTable = true
    # noClasses = true
    # noHl = false
    # style = 'github'
    # tabWidth = 2

[author]
  name = "vczyh"
  homepage = "https://zhangeek.com/"

[languages]
  # [languages.en]
  #   contentDir = "content/en"
  #   languageName = "English"
  #   weight = 1
  [languages.cn]
    contentDir = "content"
    languageName = "Chinese"
    weight = 2

[params]
mainSections = ["posts"]
headTitle = "vczyh"
disqus = "vczyh" # disqus account name
extraHead = '<script async src="https://www.googletagmanager.com/gtag/js?id=UA-xxx"></script>'
[[params.socials]]
name = "About Me"
link = "https://github.com/vczyh"
[[params.socials]]
name = "Github"
link = "https://github.com/vczyh"
postHeaderContent = ""
postFooterContent = "<br/><br/><p>Subscribe to：<a target='_blank' href='https://mailchi.mp/a1a0d59e7a19/joway'>Joway's Blog</a></p>"
# extraCSSFiles = ["css/foo.css", "css/bar.css"]
extraCSSFiles = []