# This is a basic workflow to help you get started with Actions

name: Deploy Blog

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ blog ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: blog

      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Build
        run: |
          yarn
          yarn build
      
      - name: Add KEY
        shell: bash
        env: 
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" > ~/.ssh/config
          chmod 700 ~/.ssh -R

      - name: Deploy
        run: |
          pwd
          ls -l
          cd public
          git config --global user.email "zhangeek@qq.com"
          git config --global user.name "vczyh"
          git init
          git add -A
          git commit -m deploy
          # Gitee
          git push -f git@gitee.com:vczyh/vczyh.git master:blog
        
