# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
    - vuepress-something 
    - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: vuepress-something

      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: 环境信息
        run: |
          node -v
          npm -v
          yarn -v

      - name: NPM build
        run: |
          yarn install
          yarn run build

      # - name: Deploy
      #   uses: JamesIves/github-pages-deploy-action@releases/v3
      #   with:
      #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      #     REPOSITORY_NAME: vczyh/vczyh.github.io
      #     BASE_BRANCH: vuepress-something
      #     # COMMIT_MESSAGE: 'auto deploy'
      #     BRANCH: master # The branch the action should deploy to.
      #     FOLDER: docs/.vuepress/dist # The folder the action should deploy.

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          repo: vczyh/vczyh.github.io
          target_branch: master # The branch the action should deploy to.
          build_dir: docs/.vuepress/dist # The folder the action should deploy.
